# Generated by Django 4.2.7 on 2023-11-20 19:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_comments_website_alter_post_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='websitemeta',
            options={'verbose_name_plural': 'Metadata del sitio'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='websitemeta',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
