# Generated by Django 4.2.7 on 2023-11-20 19:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_comments_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemeta',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='websitemeta',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
