# Generated by Django 4.2.7 on 2023-11-20 21:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
